input.onGesture(Gesture.Shake, () => {
    bitbot.neoClear()
    bitbot.neoSetPixelColor(5, neopixel.colors(NeoPixelColors.Red))
    bitbot.neoSetPixelColor(11, neopixel.colors(NeoPixelColors.Red))
    bitbot.neoShow()
    basic.pause(1000)
    bitbot.neoClear()
    bitbot.neoSetPixelColor(4, neopixel.colors(NeoPixelColors.Orange))
    bitbot.neoSetPixelColor(10, neopixel.colors(NeoPixelColors.Orange))
    bitbot.neoShow()
    basic.pause(1000)
    bitbot.neoClear()
    bitbot.neoSetPixelColor(3, neopixel.colors(NeoPixelColors.Green))
    bitbot.neoSetPixelColor(9, neopixel.colors(NeoPixelColors.Green))
    bitbot.neoShow()
    bitbot.buzz(1)
    basic.pause(1000)
    bitbot.buzz(0)
    bitbot.motor(bitbot.Motor.All, 1023)
    basic.pause(3000)
    bitbot.motor(bitbot.Motor.All, 0)
})
